In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.18.5


Q1:

In [8]:
l=[]
for i in range(2,50,3):
    l.append(i)
arr=np.array(l)
print(arr)
print(type(arr))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]
<class 'numpy.ndarray'>


Q2:

In [15]:
l1=[]
l2=[]
for i in range(1,6):
    l1.append(eval(input("Enter the numbers: ")))
print("\n")
for i in range(1,6):
    l2.append(eval(input("Enter the numbers: ")))
arr1=np.array(l1)
arr2=np.array(l2)
arr=np.concatenate((arr1,arr2))
print("\n")
print(arr)
print(np.sort(arr))

Enter the numbers: 5
Enter the numbers: 4
Enter the numbers: 3
Enter the numbers: 2
Enter the numbers: 1


Enter the numbers: 10
Enter the numbers: 9
Enter the numbers: 8
Enter the numbers: 7
Enter the numbers: 6


[ 5  4  3  2  1 10  9  8  7  6]
[ 1  2  3  4  5  6  7  8  9 10]


Q3:

In [42]:
arr = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
print(arr)
print("Dimension:-",arr.shape)
print("Size:-",arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension:- (3, 3)
Size:- 9


Q4:

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print("\n")
newarr = arr.reshape(4, 3)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
Q5:

In [40]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
v=np.vstack((x,y))
h=np.hstack((x,y))
print("Stack vertically:-")
print(v)
print("\nStack horizontally:-")
print(h)

Stack vertically:-
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Stack horizontally:-
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
Q6:

In [44]:
x=np.array([2,3,4,3,5,6,4,8,3,2,6])
y=np.unique(x)
print(y)
print("Count:",len(y))

[2 3 4 5 6 8]
Count: 6
